<h1>Konst- och Bruksglasföreningen</h1>

<div class="col-md-8 col-md-offset-2">
    <p>Konst- och Bruksglasföreningens webbplats är skapad av mig.</p>
    <p>Webbplatsen finns att besöka <?php echo $this->tag->linkTo( "http://www.konstochbruksglasforeningen.se/", "http://www.konstochbruksglasforeningen.se/", false ); ?>.</p>
</div>

<div class="col-md-8 col-md-offset-2">
    <figure class="figure">
        <?php echo $this->tag->image( "images/konstochbruksglasforeningen.png", "Konst- och Bruksglasföreningen", array("class" => "img-responsive") ); ?>
        <figcaption class="figure__figcaption">Konst- och Bruksglasföreningen</figcaption>
    </figure>
</div>

<div class="col-md-8 col-md-offset-2">
    <figure class="figure">
        <?php echo $this->tag->image( "images/konstochbruksglasforeningen_mobile.png", "Mobilanpassad", array("class" => "img-responsive center-block") ); ?>
        <figcaption class="figure__figcaption">Mobilanpassad</figcaption>
    </figure>
</div>