<div class="col-md-8 col-md-offset-2">

<h1>Simoxbook</h1>
<p>Simoxbook är en enkel webbaplikation skapad för att visa webbramverket <?php echo $this->tag->linkTo( "project/simox", "Simox" ) ?>.</p>
<p>I Simoxbook kan man skapa en användare, ändra i sin profil och skriva forumet.</p>
<p>En demoversion av Simoxbook finns att se <?php echo $this->tag->linkTo( "http://www.simoxbook.simonwebb.se/", "http://www.simoxbook.simonwebb.se/", false ); ?>.</p>
<p><a href="">Ladda ner källkoden till Simoxbook.</a></p>
<p>Simoxbook är skapad med delvis inspiration från INVO i Phalcons dokumentation (<?php echo $this->tag->linkTo( "https://docs.phalconphp.com/en/latest/reference/tutorial-invo.html", "https://docs.phalconphp.com/en/latest/reference/tutorial-invo.html", false ); ?>).</p>
<p>På <?php echo $this->tag->linkTo( "http://www.simoxbook.simonwebb.se/poll", "http://www.simoxbook.simonwebb.se/poll", false ); ?> finns en omröstning skapad på ett väldigt liknande sätt som i Phalcons övningsvideo (<?php echo $this->tag->linkTo( "https://vimeo.com/63022489", "https://vimeo.com/63022489", false ) ?>), men skapad i mitt egna ramverk.</p>

</div>