<!DOCTYPE html>
<html lang="sv-se">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css"> -->
        <link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet" type="text/css">
        <?php //echo $this->tag->stylesheetLink( "css/normalize.css" ); ?>
        <?php echo $this->tag->stylesheetLink( "css/bootstrap.min.css" ); ?>
        <?php echo $this->tag->stylesheetLink( "css/style.css" ); ?>
        <?php echo $this->tag->getTitle(); ?>
    </head>
    <body>
        
        <header class="header">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <div class="logo"><?php echo $this->tag->linkTo( "", "Simonwebb" ); ?></div>
                    </div>
                    <div class="col-md-4">
                        <ul class="header-links list-inline">
                            <li><a href="#minaprojekt">Mina projekt</a></li>
                            <!-- <li><a href="#ommig">Om mig</a></li> -->
                        </ul>
                    </div>
                </div>
            </div>
        </header>

        <?php echo $this->flash->output(); ?>

        <main class="main">
            <div class="container">
                <div class="row">
                    <?php echo $this->getContent(); ?>
                </div>
            </div>
        </main>
        
        <div class="presentation">
            <div class="container">
                <div class="row">
                    <div class="presentation-text col-md-8 col-md-offset-2">
                        <h2>Låt mig skapa din hemsida</h2>
                        <p>Hej! Jag heter Simon. Jag skapar hemsidor för 100 kronor i timmen.
                        <p>Kontakta mig genom formuläret.</p>
                    </div>
                    <form class="presentation-form col-md-6 col-md-offset-3">
                        <div class="row">
                            <textarea placeholder="Skriv till mig så ger jag dig en offert!" class="presentation-form__textarea"></textarea>
                            <input placeholder="Ange din e-postadress" class="presentation-form__email" type="text">
                            <input class="button button--yellow" type="submit" value="Skicka">
                        </div>
                    </form>
                </div>
            </div>
        </div>
			
        <div class="project-feature">
            <div class="container">
                <h2 id="minaprojekt">Mina projekt</h2>
                <div class="row">
                    <div class="col-md-6">
                        <div class="project-feature__section">
                            <div class="project-feature__section-image">
                                <a href="<?php echo $this->url->get( "project/simoxbook" ); ?>"><img src="<?php echo $this->url->get( "images/simoxbook.png" ); ?>" alt="Simoxbook"></a>
                            </div>
                            <h3>Simoxbook</h3>
                            <p>Skapa en profil och skriv i forumet.<br>Skapad med Simox.</p>
                            <a href="<?php echo $this->url->get( "project/simoxbook" ); ?>" class="button button--yellow">Läs mer</a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="project-feature__section">
                            <div class="project-feature__section-image">
                                <a href="<?php echo $this->url->get( "project/simox" ); ?>"><img src="<?php echo $this->url->get( "images/simox.png" ); ?>" alt="Simox"></a>
                            </div>
                            <h3>Simox</h3>
                            <p>Ett MVC webbramverk skrivet i PHP.</p>
                            <a href="<?php echo $this->url->get( "project/simox" ); ?>" class="button button--yellow">Läs mer</a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="project-feature__section">
                            <div class="project-feature__section-image">
                                <a href="<?php echo $this->url->get( "project/konstochbruksglasforeningen" ); ?>"><img src="<?php echo $this->url->get( "images/konstochbruksglasforeningen.png" ); ?>" alt="Konst- och Bruksglasföreningen"></a>
                            </div>
                            <h3>Konst- och Bruksglasföreningen</h3>
                            <p>En webbplats skapad av mig.</p>
                            <a href="<?php echo $this->url->get( "project/konstochbruksglasforeningen" ); ?>" class="button button--yellow">Läs mer</a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="project-feature__section">
                            <div class="project-feature__section-image">
                                <a href="<?php echo $this->url->get( "project/rentalmovies" ); ?>"><img src="<?php echo $this->url->get( "images/rentalmovies.png" ); ?>" alt="RentalMovies"></a>
                            </div>
                            <h3>RentalMovies</h3>
                            <p>Bläddra bland filmer, hyr en film och skapa din egna profil.</p>
                            <a href="<?php echo $this->url->get( "project/rentalmovies" ); ?>" class="button button--yellow">Läs mer</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <footer class="footer">
            <ul class="footer-links-list">
                <li class="footer-links-list__item"><a href="<?php echo $this->url->get( "project/simoxbook" ); ?>">Simoxbook</a></li>
                <li class="footer-links-list__item"><a href="<?php echo $this->url->get( "project/simox" ); ?>">Simox</a></li>
                <li class="footer-links-list__item"><a href="<?php echo $this->url->get( "project/konstochbruksglasforeningen" ); ?>">Konst- och Bruksglasföreningen</a></li>
                <li class="footer-links-list__item"><a href="<?php echo $this->url->get( "project/rentalmovies" ); ?>">RentalMovies</a></li>
            </ul>
            <p class="text-center"><a href="mailto:simon@simonwebb.se">simon@simonwebb.se</a></p>
        </footer>

        <?php echo $this->tag->javascriptInclude( "http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js", false ); ?>
        <?php echo $this->tag->javascriptInclude( "js/bootstrap.min.js" ); ?>

    </body>
</html>